version: "2.1"

services:
  php-fpm:
    container_name: php
    build: 
      context: ./php
      dockerfile: Dockerfile
    restart: always
    ports:
      - 9000:9000
    volumes_from:
      - project
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes_from:
      - project
  project:
    image: busybox
    container_name: project
    volumes:
      - ~/data/service/lnmp-docker/project:/usr/share/nginx
      - ~/data/service/lnmp-docker/nginx/conf:/etc/nginx        
